### ISSUE TITLE
Can't Load 'colourmaptest.npy'

### ISSUE THREAD

**Issue by ryangooch** [pyviz/colorcet#22]
I was hoping to test some of my colormaps with the sine grating test, replicating what the User Guide did, but have run into this problem. I've downloaded the file from the repo to my local drive, and am attempting to load it as such:

```python
import numpy as np

sine = np.load('colourmaptest.npy')
```

which produces the error:

```
UnpicklingError                           Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    427             try:
--> 428                 return pickle.load(fid, **pickle_kwargs)
    429             except Exception:

UnpicklingError: invalid load key, '\x0a'.
```

Is there something wrong with the file? Am I doing anything wrong?

**Comment by jbednar** [comment]
I believe that file is from https://github.com/matplotlib/viscm/blob/master/viscm/examples/colourmaptest.npy , but you're right that we should put it into the colorcet repo so that others can run it more easily, so please leave this open until we have a chance to do that.

**Comment by ryangooch** [comment]
Thanks for the response! After using that link, I realized that the issue was that I was saving the link to the github webpage holding the file, not the file itself. Pretty silly mistake.

**Comment by jbednar** [comment]
No problem; hope you are finding colorcet useful!
