### ISSUE TITLE
Users Guide Palettes showing non-continuous artifacts

### ISSUE THREAD

**Issue by flutefreak7** [pyviz/colorcet#30]
Several of the images in the users guide are showing strange non-continuous colors within parts of the palette:

![image](https://user-images.githubusercontent.com/2966015/56389766-05458c00-61f0-11e9-9f29-2c7bcbeb3a4b.png)

![image](https://user-images.githubusercontent.com/2966015/56389829-2dcd8600-61f0-11e9-9b97-83ff00d760ee.png)

Let me know if what I'm saying isn't visually apparent.

**Comment by jbednar** [comment]
Can you maybe edit that image in a paint program and circle the problematic areas?

**Comment by flutefreak7** [comment]
Oh wow, apparently I have a monitor that doesn't do certain colors well and I only really notice it when looking at colormaps...

![image](https://user-images.githubusercontent.com/2966015/56505421-41733800-64e1-11e9-9b95-5ead4a8b1bee.png)

The blue to green transition is all messed up in weird ways.  This is clearly a monitor or graphics card thing because my other 2 monitors show it fine.  Sorry for the noise!

**Comment by jbednar** [comment]
I'm glad that colorcet was able to reveal the problem for you!  It's good to start from a position where the colormap _should_ be uniform, so that any deviations from uniform become obvious...
