### ISSUE TITLE
Building own colormaps based on 2-3 input colors

### ISSUE THREAD

**Issue by sebhahn** [pyviz/colorcet#40]
Is it possible to build own colormaps that are perceptually uniform colormaps? E.g. simply defining 3 colors (blue, yellow, brown) and having a function which computes some colormaps samples?

**Comment by jbednar** [comment]
It's possible, but colorcet doesn't currently include any code for constructing uniform colormaps; it simply includes the colormaps generated by Peter Kovesi using the code at https://peterkovesi.com/projects/colourmaps/ .  I'd be happy to include a Python port of that code to provide such functionality, but don't have any plans to make such a port myself.  Also see https://github.com/matplotlib/viscm, which has a somewhat different definition of uniformity but is already in Python and may meet your needs.

**Comment by sebhahn** [comment]
Thanks for your help!
