### ISSUE TITLE
PyPI release of 1.0.0

### ISSUE THREAD

**Issue by jakirkham** [pyviz/colorcet#7]
Would be great to have an `sdist` on PyPI for the 1.0.0 release. This should help move packaging in conda-forge forward.

xref: https://github.com/conda-forge/staged-recipes/issues/4029

**Comment by jakirkham** [comment]
Would be nice to have the license file included if possible. ( https://github.com/bokeh/colorcet/pull/6 ) Though that might need to wait for another release.

**Comment by jbednar** [comment]
I've added the license file to the manifest, but last time I checked PyPI a month ago, none of our previous mechanisms for making releases on it were working as it was in the midst of some transition.  I can try again...

**Comment by nehaljwani** [comment]
Gentle reminder ;-)

**Comment by jbednar** [comment]
Thanks for the reminder.  I've assigned this issue to @ceball, who is setting up automated release across a dozen or so of our projects, including colorcet, and we *will* be getting to this. :-)

**Comment by jsignell** [comment]
Embarrassing that it took so long, but pypi is up to date now.
